### ISSUE TITLE
Response::with not visible in documentation

### ISSUE THREAD

**Issue by rofrol** [iron/iron-doc#10]
`fn with` isn't visible in documentation http://ironframework.io/doc/iron/response/struct.Response.html, though it is in the rs file http://ironframework.io/doc/src/iron/src/response.rs

**Comment by reem** [comment]
There are some problems with docs not updating correctly. @zzmp what's the status on this?

**Comment by zzmp** [comment]
It's a name collision when the tests compile. I've found the error, I just need to find the time to fix it.

Just keep me assigned, I'll get to it by the end of the week.

**Comment by Hoverbear** [comment]
`with` is now visible at that linked page. Closing.
