### ISSUE TITLE
Public doc server seems to be down

### ISSUE THREAD

**Issue by uniphil** [iron/iron-doc#7]
I can not connect to http://docs.ironframework.io. I tried to get there from the main iron website (http://ironframework.io/), clicking the "Docs" link at  the top right.

Seems like this might not be the desireable result of that link, which advertises itself, "Our docs are served with Iron!" :wink:

**Comment by theptrk** [comment]
Definitely not the desired result, great catch. We'll raise the alarm.

**Comment by theptrk** [comment]
@zzmp please triage this ASAP.

**Comment by zzmp** [comment]
@uniphil thnks for the heads up. The VM we're using shut down all my processes for some reason :(. It should be back up.

**Comment by uniphil** [comment]
awesome!
