### ISSUE TITLE
Link more prominently from ironframework.io

### ISSUE THREAD

**Issue by brycefisher** [iron/iron-doc#8]
I've spent a decent amount of time playing with Iron, and I only now discovered this repo. I think this may be the biggest example application that actually uses Iron.

IMHO it would be great to somehow promote this repo on ironframework.io to showcase a working a web server "in the wild".

**Comment by zzmp** [comment]
@brycefisher great idea! I'll change https://github.com/iron/iron.github.io to add the link.

The served docs need to be refreshed as well, and the server updated to use the newest refactor of iron, so this will be updated as well. I'll try to make it up-to-date by EOD. Thanks.

**Comment by brycefisher** [comment]
Np! Iron is awesome. Thanks making it!

**Comment by zzmp** [comment]
:)

We might be waiting for a less trivial example to surface instead of linking to this repo, but I'll still get to updating this by EOD. The server here is pretty straightforward, but the scripts involved to generate the content might be added confusion.

@reem bump

**Comment by reem** [comment]
I'm reluctant to link to this because it's very unintuitive and the Iron bit is basically just static-file. I'd much rather have a better example, which @mk270 from IRC is working on.

EDIT: Woops. Did not mean to close.

**Comment by brycefisher** [comment]
Totally makes sense, and I agree.

Eventually, I'd love to see ALL the middleware put together into say a blog with a contact form (no admin interface, just static content with a templating engine).

**Comment by zzmp** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/08/you-can-do-it-.gif)

**Comment by brycefisher** [comment]
Si se puede! That's the plan :-)

**Comment by Hoverbear** [comment]
Closing this, it's been 2 years and there is http://ironframework.io/doc/iron/ linked right on the front page.
